export { runDoctor } from './controller/run-doctor.js';
export type { RunDoctorRequest, RunDoctorResult } from './controller/run-doctor.js';
export { reportNode } from './controller/report-node.js';
export { reportPnpm } from './controller/report-pnpm.js';
export { reportDependencies } from './controller/report-dependencies.js';
export { reportBuild } from './controller/report-build.js';
export { reportAgent } from './controller/report-agent.js';
export { checkNodeVersion, type NodeVersionCheck } from './services/check-node-version.js';
export { checkPnpm, type PnpmCheck } from './services/check-pnpm.js';
export { detectNodeVersionManagers, type NodeVersionManagers } from './services/detect-node-version-managers.js';
export { installDependencies, type CommandCheck } from './services/install-dependencies.js';
export { buildCli } from './services/build-cli.js';
export { binaryExists } from './helpers/binary-exists.js';
export { pathExists } from './helpers/path-exists.js';
export { runSpawn } from './helpers/run-spawn.js';
export { stderrLines } from './helpers/stderr-lines.js';
export { installCommand, installHint } from './helpers/install-command.js';
export { AGENT_DEFS, INSTALLABLE_AGENTS } from './constants/agent-defs.js';
export { REQUIRED_NODE_MAJOR } from './constants/node-version.js';
export type { AgentDefinition } from './types/agent-definition.js';
export type { ShellCommandResult } from './types/shell.js';
export type { ReportLine, CheckOutcome } from './types/report.js';
