export type FlagMode = 'pty' | 'headless';

export interface FlagSpec {
  flag: string;
  kind: 'boolean' | 'value';
  sampleValue?: string;
  modes: FlagMode[];
  incompatibleWith: string[];
  forcesHeadless?: boolean;
  requiresCredentials?: boolean;
  notes?: string;
}

export const COMPOSITION_FLAGS = [
  '--composite',
  '--atomic',
  '--composition-map',
  '--composition-agent',
  '--composition-agent-mode',
  '--composition-refresh',
  '--generate-map',
  '--prompt',
] as const;

export const HEADLESS_TRIGGER_FLAGS = [
  '--auto-accept-scope',
  '--skip-analyze',
  '--skip-generate',
  '--skip-apply',
  '--yes',
  '--dry-run',
  '--print-prompt',
] as const;

export const IMPORT_FLAGS: FlagSpec[] = [
  {
    flag: '--space-id',
    kind: 'value',
    sampleValue: 'test-space',
    modes: ['headless'],
    incompatibleWith: [],
    forcesHeadless: true,
    requiresCredentials: false,
    notes: 'Providing credentials forces the headless dispatcher.',
  },
  {
    flag: '--environment-id',
    kind: 'value',
    sampleValue: 'master',
    modes: ['headless'],
    incompatibleWith: [],
    forcesHeadless: true,
  },
  {
    flag: '--cma-token',
    kind: 'value',
    sampleValue: 'test-token',
    modes: ['headless'],
    incompatibleWith: [],
    forcesHeadless: true,
  },
  {
    flag: '--project',
    kind: 'value',
    sampleValue: '.',
    modes: ['pty', 'headless'],
    incompatibleWith: ['--push-from-run', '--modify'],
  },
  {
    flag: '--out',
    kind: 'value',
    sampleValue: '/tmp/eds-out',
    modes: ['headless'],
    incompatibleWith: [],
    notes: 'Headless-only artifact directory; the wizard manages its own output.',
  },
  {
    flag: '--agent',
    kind: 'value',
    sampleValue: 'claude',
    modes: ['pty', 'headless'],
    incompatibleWith: [],
  },
  {
    flag: '--model',
    kind: 'value',
    sampleValue: 'haiku',
    modes: ['pty', 'headless'],
    incompatibleWith: [],
  },
  {
    flag: '--tokens',
    kind: 'value',
    sampleValue: '/tmp/tokens.json',
    modes: ['pty', 'headless'],
    incompatibleWith: ['--raw-tokens'],
  },
  {
    flag: '--raw-tokens',
    kind: 'value',
    sampleValue: '/tmp/raw-tokens.scss',
    modes: ['pty', 'headless'],
    incompatibleWith: ['--tokens'],
  },
  {
    flag: '--select-all',
    kind: 'boolean',
    modes: ['headless'],
    incompatibleWith: [],
  },
  {
    flag: '--select',
    kind: 'value',
    sampleValue: 'Button',
    modes: ['headless'],
    incompatibleWith: [],
  },
  {
    flag: '--deselect',
    kind: 'value',
    sampleValue: 'Icon',
    modes: ['headless'],
    incompatibleWith: [],
  },
  {
    flag: '--skip-analyze',
    kind: 'boolean',
    modes: ['headless'],
    incompatibleWith: [],
    forcesHeadless: true,
  },
  {
    flag: '--skip-generate',
    kind: 'boolean',
    modes: ['headless'],
    incompatibleWith: [],
    forcesHeadless: true,
  },
  {
    flag: '--print',
    kind: 'boolean',
    modes: ['headless'],
    incompatibleWith: [],
  },
  {
    flag: '--skip-apply',
    kind: 'boolean',
    modes: ['headless'],
    incompatibleWith: [],
    forcesHeadless: true,
  },
  {
    flag: '--no-cache',
    kind: 'boolean',
    modes: ['pty', 'headless'],
    incompatibleWith: [],
  },
  {
    flag: '--yes',
    kind: 'boolean',
    modes: ['headless'],
    incompatibleWith: [],
    forcesHeadless: true,
  },
  {
    flag: '--verbose',
    kind: 'boolean',
    modes: ['pty', 'headless'],
    incompatibleWith: [],
  },
  {
    flag: '--exclude-invalid',
    kind: 'boolean',
    modes: ['pty', 'headless'],
    incompatibleWith: [],
  },
  {
    flag: '--viewports',
    kind: 'value',
    sampleValue: '/tmp/viewports.json',
    modes: ['headless'],
    incompatibleWith: [],
  },
  {
    flag: '--host',
    kind: 'value',
    sampleValue: 'http://127.0.0.1:9999',
    modes: ['pty', 'headless'],
    incompatibleWith: [],
  },
  {
    flag: '--dry-run',
    kind: 'boolean',
    modes: ['headless'],
    incompatibleWith: [],
    forcesHeadless: true,
    notes: 'Deprecated prompt-print alias for --print-prompt; forwards dry-run and triggers headless.',
  },
  {
    flag: '--print-prompt',
    kind: 'boolean',
    modes: ['headless'],
    incompatibleWith: [],
    forcesHeadless: true,
  },
  {
    flag: '--auto-accept-scope',
    kind: 'boolean',
    modes: ['pty', 'headless'],
    incompatibleWith: [],
    notes: 'Passes the non-TTY guard; in a non-TTY run it falls through to the headless dispatcher.',
  },
  {
    flag: '--composite',
    kind: 'boolean',
    modes: ['pty', 'headless'],
    incompatibleWith: [],
    notes: 'Composition opt-in; wins over --atomic when both are passed (precedence, not an error).',
  },
  {
    flag: '--atomic',
    kind: 'boolean',
    modes: ['pty', 'headless'],
    incompatibleWith: [],
    notes: 'Default mode. Accepted for symmetry; --composite wins if both passed.',
  },
  {
    flag: '--composition-map',
    kind: 'value',
    sampleValue: '/tmp/map.json',
    modes: ['pty', 'headless'],
    incompatibleWith: [],
    notes: 'Implies --composite.',
  },
  {
    flag: '--composition-agent',
    kind: 'boolean',
    modes: ['pty', 'headless'],
    incompatibleWith: [],
    notes: 'Implies --composite.',
  },
  {
    flag: '--composition-agent-mode',
    kind: 'value',
    sampleValue: 'parser',
    modes: ['pty', 'headless'],
    incompatibleWith: [],
  },
  {
    flag: '--composition-refresh',
    kind: 'boolean',
    modes: ['pty', 'headless'],
    incompatibleWith: [],
    notes: 'Implies --composite.',
  },
  {
    flag: '--generate-map',
    kind: 'value',
    sampleValue: '/tmp/skeleton.json',
    modes: ['pty', 'headless'],
    incompatibleWith: [],
    notes: 'Implies --composite.',
  },
  {
    flag: '--prompt',
    kind: 'value',
    sampleValue: 'composition=./p.md',
    modes: ['pty', 'headless'],
    incompatibleWith: [],
  },
  {
    flag: '--auto-reject-cycles',
    kind: 'boolean',
    modes: ['pty', 'headless'],
    incompatibleWith: [],
  },
  {
    flag: '--auto-filter',
    kind: 'boolean',
    modes: ['pty', 'headless'],
    incompatibleWith: [],
    notes: 'Commander folds --auto-filter/--no-auto-filter into one boolean; last wins, no rejection guard.',
  },
  {
    flag: '--no-auto-filter',
    kind: 'boolean',
    modes: ['pty', 'headless'],
    incompatibleWith: [],
    notes: 'No-op when paired with --auto-accept-scope; not a hard rejection with --auto-filter.',
  },
  {
    flag: '--no-live-preview',
    kind: 'boolean',
    modes: ['pty'],
    incompatibleWith: [],
    notes: 'Only meaningful in the interactive wizard (live preview re-run after FieldEditor save).',
  },
  {
    flag: '--no-push',
    kind: 'boolean',
    modes: ['pty', 'headless'],
    incompatibleWith: ['--no-save', '--push-from-run'],
  },
  {
    flag: '--no-save',
    kind: 'boolean',
    modes: ['pty', 'headless'],
    incompatibleWith: ['--no-push', '--out-dir', '--on-conflict', '--push-from-run'],
  },
  {
    flag: '--out-dir',
    kind: 'value',
    sampleValue: '/tmp/eds-save',
    modes: ['pty', 'headless'],
    incompatibleWith: ['--no-save'],
  },
  {
    flag: '--on-conflict',
    kind: 'value',
    sampleValue: 'overwrite',
    modes: ['pty', 'headless'],
    incompatibleWith: ['--no-save'],
  },
  {
    flag: '--select-prompt-path',
    kind: 'value',
    sampleValue: '/tmp/select-prompt.md',
    modes: ['pty', 'headless'],
    incompatibleWith: [],
  },
  {
    flag: '--generate-prompt-path',
    kind: 'value',
    sampleValue: '/tmp/generate-prompt.md',
    modes: ['pty', 'headless'],
    incompatibleWith: [],
  },
  {
    flag: '--push-from-run',
    kind: 'value',
    sampleValue: 'run-123',
    modes: ['pty', 'headless'],
    incompatibleWith: ['--modify', '--project', '--no-save', '--no-push', '--overwrite', '--save-as-new'],
  },
  {
    flag: '--modify',
    kind: 'value',
    sampleValue: 'run-123',
    modes: ['pty'],
    incompatibleWith: ['--push-from-run', '--project'],
  },
  {
    flag: '--overwrite',
    kind: 'boolean',
    modes: ['pty'],
    incompatibleWith: ['--save-as-new', '--push-from-run'],
    notes: 'Only valid with --modify.',
  },
  {
    flag: '--save-as-new',
    kind: 'boolean',
    modes: ['pty'],
    incompatibleWith: ['--overwrite', '--push-from-run'],
    notes: 'Only valid with --modify.',
  },
  {
    flag: '--force',
    kind: 'boolean',
    modes: ['pty', 'headless'],
    incompatibleWith: [],
    notes: 'Bypasses staleness checks; paired with --push-from-run or --modify.',
  },
];
